services:
  - type: web
    name: tsahilgaan-system
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SECRET
        generateValue: true
